[project]
name = "auto-swagger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate==1.6.0",
    "annotated-types==0.7.0",
    "bitsandbytes==0.42.0",
    "blis==1.3.0",
    "catalogue==2.0.10",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "cloudpathlib==0.21.0",
    "confection==0.1.5",
    "cryptography==44.0.2",
    "cymem==2.0.11",
    "datasets>=2.14.4",
    "deprecated==1.2.18",
    "filelock==3.18.0",
    "fsspec==2025.3.2",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "huggingface-hub==0.30.2",
    "idna==3.10",
    "jinja2==3.1.6",
    "langcodes==3.5.0",
    "language-data==1.3.0",
    "marisa-trie==1.2.1",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "mdurl==0.1.2",
    "mpmath==1.3.0",
    "murmurhash==1.0.12",
    "networkx==3.4.2",
    "numpy==2.2.4",
    "packaging==25.0",
    "peft>=0.15.2",
    "pillow==11.2.1",
    "preshed==3.0.9",
    "psutil==7.0.0",
    "pycparser==2.22",
    "pydantic-core==2.33.1",
    "pygithub==2.6.1",
    "pygments==2.19.1",
    "pyjwt==2.10.1",
    "pynacl==1.5.0",
    "pyyaml==6.0.2",
    "regex==2024.11.6",
    "requests==2.32.3",
    "rich==14.0.0",
    "safetensors==0.5.3",
    "scipy==1.15.2",
    "setuptools==78.1.0",
    "shellingham==1.5.4",
    "smart-open==7.1.0",
    "smmap==5.0.2",
    "spacy==3.8.5",
    "spacy-legacy==3.0.12",
    "spacy-loggers==1.0.5",
    "srsly==2.5.1",
    "sympy==1.13.1",
    "thinc==8.3.6",
    "tokenizers==0.21.1",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "tqdm==4.67.1",
    "transformers==4.51.3",
    "typer==0.15.2",
    "typing-extensions==4.13.2",
    "typing-inspection==0.4.0",
    "urllib3==2.4.0",
    "wasabi==1.1.3",
    "weasel==0.4.1",
    "wheel>=0.45.1",
    "wrapt==1.17.2",
]

[project.scripts]
auto-swagger = "auto_swagger.main:main"
finetune = "auto_swagger.finetune.finetune:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/auto_swagger"]